version: "3.8"
services:
  data_services:
    build:
      context: .
    environment:
      - DATA_SERVICES_STORAGE=/Data_services_storage
      - DATA_SERVICES_GRAPHS=/Data_services_graphs
      - DATA_SERVICES_LOGS=/Data_services_logs
      # DATA_SERVICES_SOURCES_SPEC - optional env var - file name for a sources spec file in the storage directory
      # the default sources spec from the codebase will be used otherwise
      - DATA_SERVICES_SOURCES_SPEC
      # DATA_SERVICES_GRAPH_SPEC - optional env var - file name for a graph spec in the storage directory
      # the default graph spec from the codebase will be used otherwise
      - DATA_SERVICES_GRAPH_SPEC
      # DATA_SERVICES_TEST_MODE - optional env var - to load faster test versions
      - DATA_SERVICES_TEST_MODE
      - "DATA_SERVICES_REDIS_HOST=${DATA_SERVICES_REDIS_HOST}"
      - "DATA_SERVICES_REDIS_PORT=${DATA_SERVICES_REDIS_PORT}"
      - "DATA_SERVICES_REDIS_PASSWORD=${DATA_SERVICES_REDIS_PASSWORD}"
    volumes:
      - .:/Data_services
      - "${DATA_SERVICES_STORAGE}:/Data_services_storage"
      - "${DATA_SERVICES_GRAPHS}:/Data_services_graphs"
      - "${DATA_SERVICES_LOGS}:/Data_services_logs"
    networks:
      - ds_network
  redis:
    image: redis
    command: "redis-server --requirepass ${DATA_SERVICES_REDIS_PASSWORD}"
    ports:
      - "${DATA_SERVICES_REDIS_PORT}:${DATA_SERVICES_REDIS_PORT}"
    networks:
      - ds_network

networks:
  ds_network:
    name: data_services_network
