apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orion.fullname" . }}-app-config
  labels:
    {{- include "orion.labels" . | nindent 4 }}
data:
  env-file: |-
    OPENAI_API_KEY={{ .Values.orion.openAI.openAIKey }}